name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm build
      
      - name: Test
        run: pnpm test
      
      - name: Typecheck
        run: pnpm typecheck
      
      - name: Version and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Get the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Generate changelogs
          pnpm changelog:core
          pnpm changelog:react
          
          cd packages/core
          if [[ "$COMMIT_MSG" =~ ^feat:.*$ ]]; then
            npm version minor
          else
            npm version patch
          fi
          npm publish --access public
          
          cd ../react
          if [[ "$COMMIT_MSG" =~ ^feat:.*$ ]]; then
            npm version minor
          else
            npm version patch
          fi
          npm publish --access public
          
          # Push tags
          git push --follow-tags
